Fatec.Treinamento.Web/Controllers/PainelController.cs
using Fatec.Treinamento.Data;
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model;
using Fatec.Treinamento.Model.DTO;
using Fatec.Treinamento.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fatec.Treinamento.Web.Controllers
{
    public class PainelController : Controller
    {
        // GET: Painel
        public ActionResult Index()
        {
            UsuarioPainelViewModel listar = new UsuarioPainelViewModel();

            int idUsuario = 0;
            using (UsuarioRepository usuario = new UsuarioRepository())
            {
                var listaUsuario = usuario.ListarPorNome(User.Identity.Name);

                foreach (var item in listaUsuario)
                {
                    idUsuario = item.Id;
                }
            }

            CursoRepository repoTodos;

            using (repoTodos = new CursoRepository())
            {
                listar.Acu = repoTodos.ListarTodosCursos();
            }

            using (TreinamentoRepository repoTrein = new TreinamentoRepository())
            {
                //Recupera a qtde de pontos que o usuario tem
                try
                {
                    listar.PontosUsuario = repoTrein.PontosUsuario(idUsuario);

                }
                catch (Exception)
                {
                    listar.PontosUsuario = 0;
                   
                }

                var treinamento = repoTrein.ListarTodosTreinamentos(idUsuario);

                foreach (var item in treinamento)
                {
                    if (treinamento != null)
                    {
                        /* 
                         * Se DataInicio for não nulo e DataConclusao for nulo então 
                         * o curso está em andamento, se os dois forem não nulo então
                         * o curso está concluido
                         */
                        if (item.DataInicio.ToString() != "01/01/0001 00:00:00" & 
                            item.DataConclusao.ToString() == "01/01/0001 00:00:00")
                        {
                            foreach (var curso in listar.Acu)
                            {
                                if (item.IdCurso == curso.IdCurso)
                                {
                                    listar.CursosAndamento.Add(curso.IdCurso);
                                }                            
                            }
                        }
                        else if (item.DataInicio.ToString() != "01/01/0001 00:00:00" &
                            item.DataConclusao.ToString() != "01/01/0001 00:00:00")
                        {
                            foreach (var curso in listar.Acu)
                            {
                                if (item.IdCurso == curso.IdCurso)
                                {
                                    listar.CursosFinalizado.Add(curso.IdCurso);
                                }
                            }
                        }
                    }

                }
     
            }
            return View(listar);
        }
    }
}

Fatec.Treinamento.Web/Controllers/TrilhaController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fatec.Treinamento.Web.Controllers
{
    // Obs: Colocando o atributo [Authorize] no controller, garante que todas as actions so podem ser
    // acessadas quando o usuário estiver autorizado a utilizar.
    // Quando informo o parametro "Roles", indico que só quem tiver o perfil administrador poderá acessar.

    //[Authorize(Roles = "Administrador")]
    public class TrilhaController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var repo = new TrilhaRepository();

            var lista = repo.Listar();

            return View(lista);
        }

        [HttpPost]
        public ActionResult Criar(Trilha trilha)
        {
            var repo = new TrilhaRepository();
            var lista = repo.Inserir(trilha);

            if (lista.Id == 0)
            {
                ModelState.AddModelError("", "Erro");
            }

            return RedirectToAction("Index");
        }
    }
}

Fatec.Treinamento.Web/Views/Shared/ItensMenuAssuntos.cshtml
@model IEnumerable<Fatec.Treinamento.Model.DTO.CursosPorAssunto>

<li>@Html.ActionLink("Todos os cursos", "Index", "Curso")</li>
<li role="separator" class="divider"></li>
<li class="dropdown-header">ASSUNTOS</li>
@foreach (var item in Model)
{
    <li>@Html.ActionLink(item.NomeAssunto + " (" + item.TotalCursos + ")", "Assunto", "Curso", new { Id = item.IdCurso }, null) </li>
}

Fatec.Treinamento.Web/Views/Shared/ItensMenuTrilhas.cshtml
<li>@Html.ActionLink("Minhas Trilhas Personalizadas", "Index", "Trilha")</li>
<li>@Html.ActionLink("Trilhas Criadas pelo Gestor", "Index", "Trilha")</li>

Fatec.Treinamento.Web/Views/Shared/_Carousel.cshtml
<div id="carousel-index" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Content/Img/eLearning.png" alt="...">
        </div>
        <div class="item">
            <img src="~/Content/Img/6-elearning-best-practices-r100.png" alt="...">
        </div>
    </div>
</div>

Fatec.Treinamento.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Fatec Treinamentos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand " href='@Url.Action("Index","Home")'>
                    <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
                    <span class="aoxo"><span class="a">&Delta;</span><span class="o">O</span><span class="x">X</span><span class="q">&#9744</span></span>
                </a>
            </div>
            <div class="navbar-collapse collapse">

                @using (Html.BeginForm("Pesquisar", "Curso", FormMethod.Post, new { @class = "navbar-form navbar-left home-search-form", role = "form" }))
                {
                    <div class="form-group">
                        <div class="input-group">
                            <input id="txtPesquisaCurso" name="txtPesquisaCurso" type="text" class="form-control" placeholder="Procurar Curso...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary btn-search" type="submit" role="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                            </span>
                        </div>
                    </div>
                }

                <ul class="nav navbar-nav">                   
                    <li>@Html.ActionLink("Populares", "Populares", "Curso")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cursos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @{
                                Html.RenderAction("MenuAssuntos", "Home");
                            }
                        </ul>
                    </li>
                    @if (Request.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Trilhas <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @{
                                Html.RenderAction("MenuTrilhas", "Home");
                            }
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Fórum", "Forum", "Curso")</li>
                                }
                </ul>

                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span> &nbsp;&nbsp; @User.Identity.GetUserName() <span class="caret"></span>
                            </a>
                            @* Mostra respectivo link do painel para Usuario, Administrador ou Instrutor 
                                dependendo de quem está logado*@
                            <ul class="dropdown-menu">
                                @if (this.User.IsInRole("Administrador"))
                                {
                                    <li>@Html.ActionLink("Meu Painel(Admin)", "Index", "Painel")</li>
                                }
                                else if (this.User.IsInRole("Instrutor"))
                                {
                                    <li>@Html.ActionLink("Meu Painel(Instrutor)", "Index", "Painel")</li>/**/
                                }
                                else if (this.User.IsInRole("Usuario"))
                                {
                                    <li>@Html.ActionLink("Meu Painel(Usuario)", "Index", "Painel")</li>
                                }
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Sair", "LogOff", "Usuario")</li>
                            </ul>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Entrar", "Login", "Usuario")</li>
                        <li class="active">@Html.ActionLink("Cadastrar", "Registrar", "Usuario")</li>
                    </ul>
                }
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Fatec/Viceri</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Fatec.Treinamento.Web/Views/Shared/_ListagemCursos.cshtml
@model IEnumerable<Fatec.Treinamento.Model.DTO.AssuntoCursoUsuario>

<div class="main-content">
    <div id="tab-courses" class="clearfix search-content">
        @foreach (var item in Model)
            {
            <div class="search-results-rows clearfix">
                <div class="search-result">
                    <div class="search-result__info">
                        <div class="search-result__title">
                            <a href="@Url.Action("Detalhe", new { id = item.IdCurso })">@Html.DisplayFor(modelItem => item.Nome)</a>
                        </div>
                        <div class="row search-result__details clearfix">
                            <div class="col-sm-3 search-result__author"><text>Por </text>@Html.DisplayFor(modelItem => item.NomeAutor)</div>
                            <div class="col-md-1 search-result__level">@item.Nivel</div>
                            <div class="col-sm-2 search-result__date">@item.DataCriacao.ToString("dd/MM/yyyy")</div>
                            <div class="col-sm-2 search-result__duration show-for-medium-up">@item.TotalDuracaoCursoFormatado</div>
                            <div class="col-sm-2 search-result__rating show-for-large-up">
                                @if (item.Classificacao != 0)
                                {
                                    //Mostra qtde de estrelas conforme a classificação do curso
                                    for (int i = 0; i < item.Classificacao; i++)
                                    {
                                        <span class="glyphicon glyphicon-star estrela-dourada"></span>
                                    }
                                    for (int i = 0; i < (5-item.Classificacao); i++)
                                    {
                                        <span class="glyphicon glyphicon-star-empty estrela-dourada"></span>
                                    }
                                }
                                else
                                {
                                    for (int i = 0; i < 5; i++)
                                    {
                                        <span class="glyphicon glyphicon-star-empty "></span>
                                    }
                                }
                                <span>(@Html.DisplayFor(Model => item.QtdUsuariosVotosCurso))</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Fatec.Treinamento.Web/Views/Shared/_PainelAdmin.cshtml
@{
    ViewBag.Title = "Painel do Administrador";
    ViewBag.Author = "Fabio Massaretto";
}

<div class="painel-title">
    <div class="painel-saudacao">
        <h2>Seja bem vindo ao seu painel, @this.User.Identity.Name!</h2>
    </div>
</div>
<div class="painel-body">
    <div class="vSpacer"></div>
    <div class="painel-main">
        <div id="gerenciar-container">
            <div class="gerenciar-container-item">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Usuarios" })" class="menu-item">Gerenciar Usuários</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Cursos" })" class="menu-item">Gerenciar Curso</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Assuntos" })" class="menu-item">Gerenciar Assuntos</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Trilhas" })" class="menu-item">Gerenciar Trilhas</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Capitulos" })" class="menu-item">Gerenciar Capitulos</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Videos" })" class="menu-item">Gerenciar Videos</a></li>
                </ul>            
            </div>
            <div class="gerenciar-container-item">
                <div class="gerenciar-content-title">
                    <h3>Visão Geral</h3>
                    <hr />
                </div> 
                <div class="painel-content-body">
                    <div id="admin-box">
                        <div class="item-admin-box">
                            <h3>Usuarios</h3>
                            <hr/>
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Número de Usuários Ativos: 4</h6>
                                <h6>Número de Usuários Inativos: 1</h6>
                                <h6>Total de Usuários: 5</h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Cursos</h3>
                            <hr />
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Total de Cursos: 10</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Assuntos</h3>
                            <hr />
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Total de Assuntos: 5</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Trilhas</h3>
                            <hr />
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Total de Trilhas: 14</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Capítulos</h3>
                            <hr />
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Total de Capítulos: 23</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Videos</h3>
                            <hr />
                            <p>O sistema tem:</p>
                            <div class="item-admin-content">
                                <h6>Total de Videos: 20</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                    </div>
                </div>   
            </div>
        </div>

    </div>

</div>

Fatec.Treinamento.Web/Views/Shared/_PainelInstrutor.cshtml
@{
    ViewBag.Title = "Painel do Instrutor";
    ViewBag.Author = "Fabio Massaretto";
}

<div class="painel-title">
    <div class="painel-saudacao">
        <h2>Seja bem vindo ao seu painel, @this.User.Identity.Name!</h2>
    </div>
</div>
<div class="painel-body">
    <div class="vSpacer"></div>
    <div class="painel-main">
        <div id="gerenciar-container">
            <div class="gerenciar-container-item">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Cursos" })" class="menu-item">Gerenciar Cursos</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Assuntos" })" class="menu-item">Gerenciar Assuntos</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Capitulos" })" class="menu-item">Gerenciar Capitulos</a></li>
                    <li role="presentation"><a href="@Url.Action("Redirecionador", "Admin", new { toPage = "Videos" })" class="menu-item">Gerenciar Videos</a></li>
                </ul>
            </div>
            <div class="gerenciar-container-item">
                <div class="alert alert-success" role="alert">
                    <a href="#" class="alert-link"><b>Nova Mensagem! </b></a>
                    Você tem 1 nova mensagem!
                </div>
                <div class="gerenciar-content-title">
                    <h3>Mensagens</h3>
                    <hr />
                    <table class="table table-color">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Curso</th>
                                <th>Video</th>
                                <th>Mensagem</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Fabi Corsi</td>
                                <td>Introdução ao SQL Server</td>
                                <td>3 - T-SQL - CREATE DATABASE - Criar Banco de Dados</td>
                                <td>Olá! Estou com duvida de como fazer um Insert no SQL</td>
                                <td><a href="#" name="responder"> Responder </a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="gerenciar-content-title">
                    <h3>Visão Geral</h3>
                    <hr />
                </div>
                <div class="painel-content-body">
                    <div id="admin-box">                      
                        <div class="item-admin-box">
                            <h3>Cursos</h3>
                            <hr />
                            <p>Você Criou:</p>
                            <div class="item-admin-content">
                                <h6>Total de Cursos: 4</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Assuntos</h3>
                            <hr />
                            <p>Você Criou:</p>
                            <div class="item-admin-content">
                                <h6>Total de Assuntos: 3</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Capítulos</h3>
                            <hr />
                            <p>Você Criou:</p>
                            <div class="item-admin-content">
                                <h6>Total de Capítulos: 4</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                        <div class="item-admin-box">
                            <h3>Videos</h3>
                            <hr />
                            <p>Você Criou:</p>
                            <div class="item-admin-content">
                                <h6>Total de Videos: 10</h6>
                                <h6></h6>
                                <h6></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

Fatec.Treinamento.Web/Views/Shared/_PainelUsuario.cshtml
@model Fatec.Treinamento.Web.Models.UsuarioPainelViewModel

@{
    ViewBag.Title = "Painel do Usuário";
    ViewBag.Author = "Fabio Massaretto";
}

<div class="painel-title">
    <div class="painel-saudacao">
        <h2>Seja bem vindo ao seu painel, @this.User.Identity.Name!</h2>
    </div>
    <div class="painel-pontos">
        <div class="painel-pontos-abv-text">
            <h5>Você tem:</h5>
        </div>
        <div class="painel-pontos-inner">
            <h5>@Model.PontosUsuario</h5>
        </div>
        <div class="painel-pontos-blw-text">
            <h5>Pontos</h5>
        </div>        
    </div>    
</div>
<div class="painel-body">
    <div class="vSpacer"></div>
    <div class="painel-main">
        <div class="item-container">
            <div class="item-title">
                <h3>Cursos em andamento <span class="glyphicon glyphicon-hourglass"></span></h3>
                <div class="bar"></div>
            </div>
            <div class="item-content">
                <div class="row">
                    <div class="col-xs-6 col-md-3" id="curso-box">
                        @foreach (var item in Model.CursosAndamento)
                        {
                            foreach (var model in Model.Acu)
                            {
                                if (item.Equals(model.IdCurso))
                                {
                                    <div class="item-curso-box">
                                        <a href="@Url.Action("Detalhe", "Curso", new { id = model.IdCurso })" @*class="thumbnail"*@>@Html.DisplayFor(modelItem => model.Nome)</a>
                                    </div>
                                }
                            }
                        }
                    </div>                  
                </div>
            </div>
        </div>
        <div class="item-container">
            <div class="item-title">
                <h3>Cursos completados <span class="glyphicon glyphicon-ok"></span></h3>
                <div class="bar"></div>
            </div>
            <div class="item-content">
                <div class="row">
                    <div class="col-xs-6 col-md-3" id="curso-box">
                        @foreach (var item in Model.CursosFinalizado)
                        {
                            foreach (var model in Model.Acu)
                            {
                                if (item.Equals(model.IdCurso))
                                {
                                    <div class="item-curso-box">
                                        <a href="@Url.Action("Detalhe", "Curso", new { id = model.IdCurso })" @*class="thumbnail"*@>@Html.DisplayFor(modelItem => model.Nome)</a> |
                                        <a href="#">Certificado</a>
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="item-container">
            <div class="item-title">
                <h3>Você tem interesse nos seguintes cursos <span class="glyphicon glyphicon-star"></span></h3>
                <div class="bar"></div>
            </div>
            <div class="item-content">
                <div class="row">
                    <div class="col-xs-6 col-md-3" id="curso-box">
                        @foreach (var item in Model.CursosFavoritos)
                        {
                            foreach (var model in Model.Acu)
                            {
                                if (item.Equals(model.IdCurso))
                                {
                                    <div class="item-curso-box">
                                        <a href="@Url.Action("Detalhe", "Curso", new { id = model.IdCurso })" @*class="thumbnail"*@>@Html.DisplayFor(modelItem => model.Nome)</a>
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>