Fatec.Treinamento.Web/Models/AdminCursoViewModel.cs
using Fatec.Treinamento.Model;
using Fatec.Treinamento.Model.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fatec.Treinamento.Web.Models
{
    public class AdminCursoViewModel
    {
        public AssuntoCursoUsuario Acu { get; set; }
        public IEnumerable<SelectListItem> ListaUsuarios { get; set; }
        public IEnumerable<SelectListItem> ListaAssunto { get; set; }

        public HttpPostedFileBase Img { get; set; }

        public IList<SelectListItem> Niveis { get; set; }

        public AdminCursoViewModel()
        {
            var data = new[]{
                 new SelectListItem{ Value="Iniciante",Text="Iniciante"},
                 new SelectListItem{ Value="Intermediário",Text="Intermediário"},
                 new SelectListItem{ Value="Avançado",Text="Avançado"}
             };

            Niveis = data.ToList();
        }

        //public List<HttpPostedFileBase> Files { get; set; }

        //public AdminCursoViewModel(){
        //    Files = new List<HttpPostedFileBase>();    
        //}

    }
}

Fatec.Treinamento.Web/Controllers/AdminCursosController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model.DTO;
using Fatec.Treinamento.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fatec.Treinamento.Web.Controllers
{
    public class AdminCursosController : Controller
    {
        // GET: AdminCursos
        [HttpGet]
        public ActionResult Index()
        {
            using (var repo = new CursoRepository())
            {
                var lista = repo.ListarTodosCursos();
                return View(lista);
            }
        }

        [HttpGet]
        public ActionResult Obter(int id)
        {
            using (var repo = new CursoRepository())
            {
                var lista = repo.Obter(id);
                return View(lista);
            }          
        }

        [HttpGet]
        public ActionResult Criar()
        {
            var model = new AdminCursoViewModel();
            //Salvo os usuarios a guardo na variavel listaUsuario
            using (var repoUser = new AdminCursoRepository())
            {
                var listaUsuario = repoUser.ListaUsuario();

                model.ListaUsuarios = (from x in listaUsuario
                                       select new SelectListItem
                                       {
                                           Text = x.Nome,
                                           Value = x.Id.ToString()
                                       });
            }

            //Salvo os assuntos a guardo na variavel listaAssunto
            using (var repoAssunto = new AdminCursoRepository())
            {
                var listaAssunto = repoAssunto.ListaAssunto();

                model.ListaAssunto = (from x in listaAssunto
                                      select new SelectListItem
                                      {
                                          Text = x.Nome,
                                          Value = x.Id.ToString()
                                      });
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Criar(AdminCursoViewModel model)
        {
            using (var repo = new AdminCursoRepository())
            {
                model.Acu.Img = model.Img.FileName.ToString();
                var inserido = repo.Inserir(model.Acu);


                if (inserido.IdCurso == 0)
                {
                    ModelState.AddModelError("", "Erro");
                }


                if (Request.Files.Count > 0)
                {
                    //var file = Request.Files[0];
                    if (ModelState.IsValid)
                    {
                       //model.Acu.Img = model.Img.FileName.ToString();
                        var filename = Path.GetFileName(model.Img.FileName);
                        var shortPath = "/Content/Img/Cursos/" + model.Acu.Nome;
                        var path = Path.Combine(Server.MapPath(shortPath), filename);

                        //Verifica se não existe o diretorio então cria o diretorio
                        if (!Directory.Exists(Server.MapPath(shortPath)))
                        {
                            var directory = Directory.CreateDirectory(Server.MapPath(shortPath));
                        }

                        model.Img.SaveAs(path);
                    }               
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var model = new AdminCursoViewModel();

            using (var repoUser = new AdminCursoRepository())
            {
                model.Acu = repoUser.Obter(id);
                var listaUsuario = repoUser.ListaUsuario();
                model.Acu.UsuarioSelecionado = model.Acu.IdAutor;

                model.ListaUsuarios = (from x in listaUsuario select new SelectListItem {
                    Text = x.Nome,
                    Value = x.Id.ToString(),
                    Selected = model.Acu.NomeAutor == x.Nome
                });
            }


            using (var repoAssunto = new AdminCursoRepository())
            {
                model.Acu.AssuntoSelecionado = model.Acu.IdAssunto;

                var listaAssunto = repoAssunto.ListaAssunto();

                model.ListaAssunto = (from x in listaAssunto
                                       select new SelectListItem
                                       {
                                           Text = x.Nome,
                                           Value = x.Id.ToString(),
                                           Selected = model.Acu.NomeAssunto == x.Nome
                                       });
            }

                return View(model);
        }

        [HttpPost]
        public ActionResult Editar(AdminCursoViewModel model)
        {
            using (var repo = new AdminCursoRepository())
            {
                var fileNameOld = repo.Obter(model.Acu.IdCurso);

                var shortPathOld = "/Content/Img/Cursos/" + fileNameOld.Nome;


                model.Acu.Img = model.Img.FileName.ToString();
                repo.Atualizar(model.Acu);

                if (Request.Files.Count > 0)
                {
                    //var file = Request.Files[0];
                    if (ModelState.IsValid)
                    {
                        var filename = Path.GetFileName(model.Img.FileName);
                        var shortPath = "/Content/Img/Cursos/" + model.Acu.Nome;
                        var path = Path.Combine(Server.MapPath(shortPath), filename);

                        if (Directory.Exists(Server.MapPath(shortPathOld)))
                        {
                            if(shortPathOld != shortPath)
                                Directory.Move(Server.MapPath(shortPathOld), Server.MapPath(shortPath));
                        }else
                        {
                            Directory.CreateDirectory(Server.MapPath(shortPath));
                        }

                        model.Img.SaveAs(path);
                        //Verifica se não existe o diretorio então cria o diretorio
                       

                    }
                }
                    return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Deletar(int id)
        {
            using (var repo = new CursoRepository())
            {
                var curso = repo.Obter(id);

                return View(curso);
            }
        }

        [HttpPost]
        public ActionResult Deletar(AssuntoCursoUsuario acu)
        {
            using (var repo = new AdminCursoRepository())
            {
                repo.Excluir(acu);
            }
            return RedirectToAction("Index");
        }

    }
}

Fatec.Treinamento.Web/Views/AdminCursos/Criar.cshtml
@model Fatec.Treinamento.Web.Models.AdminCursoViewModel

@{
    ViewBag.Title = "Criar";
    ViewBag.Author = "Fabio Massaretto";
}

<h2>Criar</h2>

@using (Html.BeginForm("Criar", "AdminCursos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Criar Novo Curso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acu.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.NomeAutor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.Acu.UsuarioSelecionado, Model.ListaUsuarios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.NomeAutor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.NomeAssunto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.Acu.AssuntoSelecionado, Model.ListaAssunto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.NomeAssunto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Acu.Descricao, new { htmlAttributes = new { @class = "form-control textarea" } })
                @Html.ValidationMessageFor(model => model.Acu.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acu.Nivel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.Nivel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Img, "", new { type = "file", name = "Img", accept = "image/*", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fatec.Treinamento.Web/Views/AdminCursos/Deletar.cshtml
@model Fatec.Treinamento.Model.DTO.AssuntoCursoUsuario

@{
    ViewBag.Title = "Deletar";
    ViewBag.Author = "Fabio Massaretto";
}

<h2>Deletar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AssuntoCursoUsuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdAutor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdAssunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdAssunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeAssunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeAssunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeAutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeAutor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Classificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classificacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fatec.Treinamento.Web/Views/AdminCursos/Editar.cshtml
@model Fatec.Treinamento.Web.Models.AdminCursoViewModel

@using (Html.BeginForm("Editar", "AdminCursos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Curso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(Model => Model.Acu.IdCurso)
        @Html.HiddenFor(Model => Model.Acu.AssuntoSelecionado)
        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acu.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.NomeAutor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.Acu.UsuarioSelecionado, Model.ListaUsuarios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.NomeAutor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.NomeAssunto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.Acu.AssuntoSelecionado, Model.ListaAssunto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.NomeAssunto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Acu.Descricao, new { htmlAttributes = new { @class = "form-control textarea" } })
                @Html.ValidationMessageFor(model => model.Acu.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Acu.DataCriacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acu.DataCriacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acu.DataCriacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acu.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(c => c.Acu.Nivel, Model.Niveis, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.EditorFor(model => model.Acu.Nivel, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Acu.Nivel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Acu.Img, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextBoxFor(model => model.Img, "", new { type = "file", name = "Img", accept = "image/*", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

Fatec.Treinamento.Web/Views/AdminCursos/Index.cshtml
@model IEnumerable<Fatec.Treinamento.Model.DTO.AssuntoCursoUsuario>

@{
    ViewBag.Title = "Gerenciar Cursos";
    ViewBag.Author = "Fabio Massaretto";
}

<h2>Gerenciar Cursos</h2>

<p>
    @Html.ActionLink("Criar Novo Curso", "Criar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeAssunto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeAutor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCriacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Classificacao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeAssunto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeAutor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCriacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Classificacao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IdCurso }) |
            @Html.ActionLink("Deletar", "Deletar", new { id=item.IdCurso })
        </td>
    </tr>
}

</table>